site_name: Odido Community Wiki
site_url: https://odido-community.github.io/
nav:
  - Home: index.md
  - Odido Hardware:
    - Modems:
      - Zyxel T50: hardware/zyxel-vmg8825.md
      - Zyxel T54: hardware/zyxel-dx5401.md
      - Zyxel T56: hardware/zyxel-ex5601.md
      - Zyxel T75: hardware/zyxel-ex7501.md
      - Zyxel NR5307: hardware/zyxel-nr5307.md
    - Access Points:
      - Zyxel WX5600-T0: hardware/zyxel-wx5600.md
      - Zyxel WAP6807: hardware/zyxel-wap6807.md
  - Own Equipment:
    - Routers:
      - Mikrotik: third-party/mikrotik.md
  - Contributing: contributing.md

theme:
  name: material
  features:
    - search.suggest
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.footnote.tooltips


  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption


plugins:
  - search
  - social

copyright: Copyright &copy; 2025 Odido Community

repo_url: https://github.com/odido-community/wiki
repo_name: odido-community/wiki
edit_uri: edit/master/docs/